"use client";
import {
  Croissant,
  Cookie,
  Cake,
  ShieldCheck,
  Wind,
  Droplets,
  Layers,
  Microscope,
  Settings2,
  Headphones,
  UtensilsCrossed,
  Milk,
  Beef,
  Sandwich,
  Utensils,
  Package,
  IceCream2,
  GlassWater,
  Thermometer,
  FlaskConical,
  Drumstick,
  ChefHat,
  Snowflake,
  BookOpen,
  TestTube,
  Factory,
  Search,
  Target,
  RefreshCw,
  MessageSquare,
  Truck,
  Users,
  Lightbulb,
  Rocket,
  BadgeCheck,
} from "lucide-react";

export const iconMap = {
  Croissant,
  Cookie,
  Cake,
  ShieldCheck,
  Wind,
  Droplets,
  Layers,
  Microscope,
  Settings2,
  Headphones,
  UtensilsCrossed,
  Milk,
  Beef,
  Sandwich,
  Utensils,
  Package,
  IceCream2,
  GlassWater,
  Thermometer,
  FlaskConical,
  Drumstick,
  ChefHat,
  Snowflake,
  BookOpen,
  TestTube,
  Factory,
  Search,
  Target,
  RefreshCw,
  MessageSquare,
  Truck,
  Users,
  Lightbulb,
  Rocket,
  BadgeCheck,
};

export type IconName = keyof typeof iconMap;

export function GCIcon({ name, className, style }: { name: IconName; className?: string; style?: React.CSSProperties }) {
  const IconComponent = iconMap[name];
  if (!IconComponent) return null;
  return <IconComponent className={className} style={style} />;
}
